services:
  gru:
    build:
      context: ./GRU_Sentiment
    ports:
      - "5004:5004"

  word2vec:
    build:
      context: ./word2vec_lstm_Model
    ports:
      - "5003:5003"

  vgg16:
    build:
      context: ./VGG16_FastApI
    ports:
      - "5005:5005"

  cnn:
    build:
      context: ./cnn_app
    ports:
      - "5006:5006"

  frontend:
    build:
      context: ./HTML/flask-app-container
    ports:
      - "5002:5002"
    depends_on:
      - gru
      - word2vec
      - vgg16
      - cnn
